#pragma once

#include "utf.hpp"

struct ACBTraits {
	static constexpr std::array<std::string_view, 3> Fields = {"CueTable", "WaveformTable", "SynthTable"};
	using Entry = std::tuple<uint64_t, uint64_t, uint64_t>;
};

class ACB : public UTFTable<ACBTraits> {
public:
	using Base = UTFTable<ACBTraits>;
	using Base::Base;

	using Base::operator<<;
	using Base::operator>>;
};

struct TopLevelAcbTraits {
	static constexpr std::array<std::string_view, 96> OtherFields = {
		"AcbGuid",
		"AcbVolume",
		"AcfMd5Hash",
		"AcfReferenceTable",
		"ActionTrackTable",
		"AisacControlNameTable",
		"AisacNameTable",
		"AisacTable",
		"AutoModulationTable",
		"AwbFile",
		"BeatSyncInfoTable",
		"BlockSequenceTable",
		"BlockTable",
		"CategoryExtension",
		"CharacterEncodingType",
		"CueLimitWorkTable",
		"CueNameTable",
		"CuePriorityType",
		"CueTable",
		"EventTable",
		"FileIdentifier",
		"GlobalAisacReferenceTable",
		"GraphTable",
		"InstrumentPluginParameterTable",
		"InstrumentPluginTrackTable",
		"LipsMorphTable",
		"MIDITrackTable",
		"Name",
		"NumCueLimit",
		"NumCueLimitListWorks",
		"NumCueLimitNodeWorks",
		"OutsideLinkTable",
		"PaddingArea",
		"ParameterAction",
		"ParameterActionCondition",
		"ProjectKey",
		"R0",
		"R1",
		"R10",
		"R11",
		"R12",
		"R13",
		"R14",
		"R15",
		"R16",
		"R17",
		"R18",
		"R19",
		"R2",
		"R20",
		"R21",
		"R22",
		"R23",
		"R24",
		"R25",
		"R26",
		"R27",
		"R28",
		"R29",
		"R3",
		"R30",
		"R31",
		"R4",
		"R5",
		"R6",
		"R7",
		"R8",
		"R9",
		"SeqCommandTable",
		"SeqParameterPalletTable",
		"SequenceTable",
		"Size",
		"SoundGeneratorTable",
		"SoundInstruments",
		"SoundProgramBankCommandTable",
		"SoundProgramBankKey",
		"StopAction",
		"StreamAwbAfs2Header",
		"StreamAwbHash",
		"StreamAwbTocWork",
		"StreamAwbTocWorkOld",
		"StreamAwbTocWork_Old",
		"StringValueTable",
		"SynthCommandTable",
		"SynthParameterPalletTable",
		"SynthTable",
		"Target",
		"TrackCommandTable",
		"TrackEventTable",
		"TrackParameterPalletTable",
		"TrackTable",
		"Type",
		"Version",
		"VersionString",
		"WaveformExtensionDataTable",
		"WaveformTable"};
};